openapi: 3.0.0
info:
  title: Book Management API
  version: 1.0.0
servers:
  - url: http://localhost:5555
paths:
  /books:
    get:
      summary: Get all books
      responses:
        '200':
          description: Success
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                publishedYear:
                  type: integer
      responses:
        '201':
          description: Book created
  /books/{id}:
    get:
      summary: Get book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
        '404':
          description: Book not found
    put:
      summary: Update a book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                author:
                  type: string
                publishedYear:
                  type: integer
      responses:
        '200':
          description: Updated book
    delete:
      summary: Delete a book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Deleted
